# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Install dependencies
      run: dotnet restore ./src/FluentEndurance.sln
    - name: Build
      run: dotnet build --configuration Release --no-restore ./src/FluentEndurance.sln
    - name: Test samples
      run: dotnet test --no-restore --verbosity normal ./src/FluentEndurance.Samples/FluentEndurance.Samples.csproj
    - name: Test unit tests
      run: dotnet test --no-restore --verbosity normal ./test/FluentEndurance.Tests/FluentEndurance.Tests.csproj
