name: .NET Core

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies
      run: dotnet restore ./src/FluentEndurance.sln
    - name: Build
      run: dotnet build --configuration Release --no-restore ./src/FluentEndurance.sln
    - name: Test samples
      run: dotnet test --no-restore --verbosity normal ./src/FluentEndurance.Samples/FluentEndurance.Samples.csproj
    - name: Test unit tests
      run: dotnet test --no-restore --verbosity normal ./test/FluentEndurance.Tests/FluentEndurance.Tests.csproj
