name: Publish NuGet
uses: brandedoutcast/publish-nuget@v2.5.5
with:
  PROJECT_FILE_PATH: ./src/FluentEndurance/FluentEndurance.csproj
  PACKAGE_NAME: FluentEndurance
  NUGET_KEY: ${{secrets.NUGET_PUBLISHER_KEY}}
